version: 2.1

orbs:
    disable-rerun: johnstonjacob/disable-rerun@dev:alpha
    cli: circleci/circleci-cli@0.1.2
    orb-tools: circleci/orb-tools@8.1.0


commands:
    disable-rerun-tests:
        description: "Verifies insertion and deletion of S3 object"
        steps:
            - disable-rerun/check-build-ran
            - disable-rerun/mark-build-ran
            - disable-rerun/check-build-ran:
                test-override: true
            - disable-rerun/unmark-build-ran

jobs:
    test-orb:
        docker:
            - image: circleci/golang:1.12
        steps:
            - disable-rerun-tests

workflows:
    lint_pack-validate_publish-dev:
        jobs:
            - orb-tools/lint
            - orb-tools/pack:
                requires:
                    - orb-tools/lint
            - orb-tools/publish-dev:
                orb-name: johnstonjacob/disable-rerun
                context: ORB-PUBLISHING
                requires:
                    - orb-tools/pack
            - orb-tools/trigger-integration-workflow:
                name: trigger-integration-dev
                context: ORB-PUBLISHING
                ssh-fingerprints: 68:22:fd:bc:5d:88:d8:0f:31:7e:49:f1:df:da:88:1a
                requires:
                    - orb-tools/publish-dev
                filters:
                    branches:
                      ignore: master

            - orb-tools/trigger-integration-workflow:
                  name: trigger-integration-master
                  context: ORB-PUBLISHING
                  ssh-fingerprints: 68:22:fd:bc:5d:88:d8:0f:31:7e:49:f1:df:da:88:1a
                  tag: master
                  requires:
                      - orb-tools/publish-dev
                  filters:
                      branches:
                        only: master
    integration-tests_prod-deploy:
        jobs:
            - test-orb:
                context: ORB-PUBLISHING
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /integration-.*/
            - orb-tools/dev-promote-prod:
                name: dev-promote-patch
                orb-name: johnstonjacob/disable-rerun
                context: ORB-PUBLISHING
                requires:
                    - test-orb
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /master-patch.*/
            - orb-tools/dev-promote-prod:
                name: dev-promote-minor
                orb-name: johnstonjacob/disable-rerun
                context: ORB-PUBLISHING
                requires:
                    - test-orb
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /master-minor.*/
            - orb-tools/dev-promote-prod:
                name: dev-promote-major
                orb-name: johnstonjacob/disable-rerun
                context: ORB-PUBLISHING
                requires:
                    - test-orb
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /master-minor.*/
